on:
  workflow_dispatch:

test-muscle5:
    name: Reproduce Mamba issue

    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: 3.10
          channels: conda-forge,defaults
