on:
  workflow_dispatch:

jobs:
  mamba-issue:
    name: Reproduce Mamba issue
    
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-20.04, ubuntu-22.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: ${{ matrix.version }}
          channels: conda-forge,defaults
